### ISSUE TITLE
Support retreiving specific version of a secret from the K/V engine

### ISSUE THREAD

**Issue by RichiCoder1** [RichiCoder1/vault-action#13]
`my-secret@2 secret | SECRET`

**Comment by fairclothjm** [comment]
Thank you for submitting this request! For others who are interested in this, please stick a 👍 on this issue. We’re currently developing an internal process to review and prioritize feature requests.

**Comment by emanuelzapata** [comment]
Did this ever get worked on? If so are there any samples of how this can be implemented somewhere?

**Comment by james-jasvin** [comment]
Hey @emanuelzapata, I just tried it out and the following logic works for fetching a secret for a specific version using the `vault-action` in a Github Actions workflow!

```
- name: Import Secrets
  id: import-secrets
  uses: hashicorp/vault-action@v2
  with:
    url: https://vault.mycompany.com:8200
    token: ${{ secrets.VAULT_TOKEN }}
    caCertificate: ${{ secrets.VAULT_CA_CERT }}
    secrets: |
      <path-to-secret-on-vault>?version=3 secret_name | SECRET_NAME_ON_GITHUB_ENV
```

I guess this accomplishes the feature that @RichiCoder1 was requesting for and this issue can be closed with this resolution
