### ISSUE TITLE
Having trouble with using the retrieved data in the following steps

### ISSUE THREAD

**Issue by Emmawaterman** [RichiCoder1/vault-action#16]
Hi thanks for sharing this action. I tried to use this actions to retrieve tokens from out vault and use it in the following steps. I have met several problems,
1. Somehow the set-env command generated by this action has a `,` after the name field in the command as
   "::set-env name=action_state,::yellow"
2. I tried to remove the comma but it still doesn't seem to work. the way I use in the following steps is "steps.login-vault.env.{name_of_token}"
 What is the recommended way to use the token retrieved in the following steps? Are the secrets being outputted? because I tried to use "steps.login-vault.outputs.{name_of_token}" still doesn't seem to work. btw, "login-vault" is the id for the login step that I used your actions for. And I can already see the token being retrieved from the debugging mode in pipeline.

**Comment by Emmawaterman** [comment]
Ended up fixing the problem by editing the source code https://github.com/RichiCoder1/vault-action/blob/master/dist/index.js#L4166 to

**Comment by Emmawaterman** [comment]
Don't know if this is intended or if there's another way to do this.

**Comment by RichiCoder1** [comment]
Howdy!

This action doesn't use outputs, but rather sets the environment variable for each following action executed in the job. So, for https://github.com/RichiCoder1/vault-action#simple-key, if you ran:
```yaml
  - run: echo "$NPMTOKEN"
```
it'd print out the secret value.

As for why it has a comma, I'm not sure. Could you post the `with:`?

**Comment by Emmawaterman** [comment]
```
with:
        url: https://vault-prd.dv.nyt.net
        method: approle
        roleId: ${{ secrets.ROLEID }}
        secretId: ${{ secrets.SECRETID }}
        kv-version: 1
        namespace: {namespace}
        secrets: {path}/gcs_push_encrypted value | vault_token

```
And the right way to use the env var in with is just `$NPMTOKEN`?
