### ISSUE TITLE
Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by tiferrei** [RichiCoder1/vault-action#2]
Hi,
Awesome action! I've been having some dificulties using it, as it doesn't seem to find the core action.
Here's my step:
```yaml
- if: github.ref == 'refs/heads/develop'
      name: Import Secrets From Stage Vault
      uses: RichiCoder1/vault-action@v0.2.1
      with:
        url: <URL HERE>
        token: ${{ secrets.STAGE_VAULT_TOKEN }}
        secrets: |
          secret/ops/ci DOCKER_PASSWORD | DOCKER_PASSWORD;
          secret/ops/ci DOCKER_REGISTRY | DOCKER_REGISTRY;
          secret/ops/ci DOCKER_USER | DOCKER_USER;
          secret/ops/ci NPM_REGISTRY | NPM_REGISTRY;
          secret/ops/ci NPM_TOKEN | NPM_TOKEN;
```

And here's the output of the step:
```
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/RichiCoder1/vault-action/v0.2.1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/runner/work/_actions/RichiCoder1/vault-action/v0.2.1/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/RichiCoder1/vault-action/v0.2.1/index.js'
  ]
}
##[error]Node run failed with exit code 1
```

Thanks!
