### ISSUE TITLE
[FEAT] Add ability to specify dynamic paths for secrets

### ISSUE THREAD

**Issue by maxdanilov** [RichiCoder1/vault-action#63]
**Is your feature request related to a problem? Please describe.**

Currently, one can only fetch secrets with predefined paths. I'd like to see the ability to obtain secrets with dynamically generated paths as well.

**Describe the solution you'd like**

For instance, this secret name is generated based on the value of an environment variable:
```
      - name: Import Secrets
        id: secrets
        uses: RichiCoder1/vault-action@v1.0.1
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            common/github.com/actions/${{ env.CLUSTER_ENV }} GCP_SA_KEY;
```

**Describe alternatives you've considered**
None.
